name: test1

on: 
  release:
    types: [created,published]

jobs:
    
  mother-of-all-steps:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3